create table if not exists public.projects (
  slug text primary key,
  name text not null,
  summary text not null,
  description text not null,
  categories text[] not null default '{}',
  technology_heading text,
  features text[] not null default '{}',
  contribution text,
  status text,
  planned text[] not null default '{}',
  metrics jsonb not null default '[]'::jsonb,
  related_project_slugs text[] not null default '{}',
  sort_order integer not null default 0,
  published boolean not null default true,
  constraint projects_categories_valid check (
    categories <@ array[
      'Featured', 'Full-stack', 'Frontend', 'Backend', 'AI', 'Data',
      'University', 'Personal', 'Startup'
    ]::text[]
  )
);

alter table public.projects
  add column if not exists technology_heading text;

create table if not exists public.technologies (
  id bigint generated by default as identity primary key,
  name text not null unique
);

create table if not exists public.project_technologies (
  project_slug text not null references public.projects(slug) on delete cascade,
  technology_id bigint not null references public.technologies(id) on delete cascade,
  sort_order integer not null default 0,
  primary key (project_slug, technology_id)
);

create table if not exists public.experiences (
  slug text primary key,
  organization text not null,
  role text not null,
  start_date date not null,
  end_date date,
  summary text not null,
  responsibilities text[] not null default '{}',
  sort_order integer not null default 0,
  published boolean not null default true
);

create table if not exists public.experience_technologies (
  experience_slug text not null references public.experiences(slug) on delete cascade,
  technology_id bigint not null references public.technologies(id) on delete cascade,
  sort_order integer not null default 0,
  primary key (experience_slug, technology_id)
);

create table if not exists public.project_images (
  id bigint generated by default as identity primary key,
  project_slug text not null references public.projects(slug) on delete cascade,
  src text not null,
  alt text not null,
  caption text,
  sort_order integer not null default 0
);

create table if not exists public.events (
  slug text primary key,
  name text not null,
  organization text not null,
  type text not null,
  date_label text,
  description text not null,
  learning text[] not null default '{}',
  people jsonb not null default '[]'::jsonb,
  related_project_slug text references public.projects(slug) on delete set null,
  sort_order integer not null default 0,
  published boolean not null default true
);

create table if not exists public.event_tags (
  id bigint generated by default as identity primary key,
  event_slug text not null references public.events(slug) on delete cascade,
  tag text not null,
  sort_order integer not null default 0,
  unique (event_slug, tag)
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  entity_type text not null check (entity_type in ('project', 'experience', 'event', 'profile')),
  entity_slug text,
  kind text not null,
  label text not null,
  url text not null,
  sort_order integer not null default 0
);

alter table public.projects enable row level security;
alter table public.technologies enable row level security;
alter table public.project_technologies enable row level security;
alter table public.experience_technologies enable row level security;
alter table public.project_images enable row level security;
alter table public.experiences enable row level security;
alter table public.events enable row level security;
alter table public.event_tags enable row level security;
alter table public.links enable row level security;

drop policy if exists "Public can read published projects" on public.projects;
create policy "Public can read published projects" on public.projects
  for select to anon, authenticated using (published);
drop policy if exists "Public can read technologies" on public.technologies;
create policy "Public can read technologies" on public.technologies
  for select to anon, authenticated using (true);
drop policy if exists "Public can read project technologies" on public.project_technologies;
create policy "Public can read project technologies" on public.project_technologies
  for select to anon, authenticated using (
    exists (
      select 1 from public.projects
      where projects.slug = project_technologies.project_slug and projects.published
    )
  );
drop policy if exists "Public can read experience technologies" on public.experience_technologies;
create policy "Public can read experience technologies" on public.experience_technologies
  for select to anon, authenticated using (
    exists (
      select 1 from public.experiences
      where experiences.slug = experience_technologies.experience_slug and experiences.published
    )
  );
drop policy if exists "Public can read project images" on public.project_images;
create policy "Public can read project images" on public.project_images
  for select to anon, authenticated using (
    exists (
      select 1 from public.projects
      where projects.slug = project_images.project_slug and projects.published
    )
  );
drop policy if exists "Public can read published experiences" on public.experiences;
create policy "Public can read published experiences" on public.experiences
  for select to anon, authenticated using (published);
drop policy if exists "Public can read published events" on public.events;
create policy "Public can read published events" on public.events
  for select to anon, authenticated using (published);
drop policy if exists "Public can read event tags" on public.event_tags;
create policy "Public can read event tags" on public.event_tags
  for select to anon, authenticated using (
    exists (
      select 1 from public.events
      where events.slug = event_tags.event_slug and events.published
    )
  );
drop policy if exists "Public can read links" on public.links;
create policy "Public can read links" on public.links
  for select to anon, authenticated using (true);

grant select on public.projects, public.technologies, public.project_technologies,
  public.experience_technologies, public.project_images, public.experiences,
  public.events, public.event_tags, public.links to anon, authenticated;

insert into public.projects (
  slug, name, summary, description, categories, technology_heading, features, contribution, status,
  planned, metrics, related_project_slugs, sort_order
) values
(
  'pickbox', 'PickBox',
  'A surplus-food platform connecting local food businesses with customers looking for more affordable meals.',
  'PickBox aims to reduce food waste by helping restaurants, bakeries, cafes, and potentially hotels offer surplus food to customers. The product concepts include Deals and MysteryBoxes.',
  array['Featured', 'Full-stack', 'Startup'],
  'Potential / current technology direction',
  array['Deals', 'MysteryBox'],
  'Built the PickBox website and MVP before Pangstart, then continued developing the product during and after the program.',
  'The MVP is mostly finished and needs further testing and improvements.',
  array['Continue product development.', 'Explore a mobile application with Expo / React Native.'],
  '[]'::jsonb,
  array['house-of-shawarma', 'sallora'], 1
),
(
  'house-of-shawarma', 'House of Shawarma',
  'An online ordering platform developed for a restaurant, with customer ordering and restaurant administration features.',
  'A real restaurant ordering platform with product and order management, discounts, opening hours, restaurant status, and an administration area.',
  array['Featured', 'Full-stack'],
  null,
  array[
    'Online ordering, products, and orders',
    'Discounts, opening hours, and restaurant status',
    'Admin dashboard and live new-order page',
    'Sound notification for new orders',
    'Stripe integration',
    'Server-side validation and webhooks'
  ],
  null, null, '{}',
  '[{"label":"Visits","value":"587+","context":"Historical project metric"},{"label":"Views","value":"1,332+","context":"Historical project metric"}]'::jsonb,
  array['pickbox', 'sallora'], 2
),
(
  'fixtech', 'FixTech',
  'Website and product development work for FixTech AS, spanning catalog, repair, administration, and data features.',
  'Professional software development work at FixTech AS, including website development, product/catalog functionality, repair-related functionality, APIs, data management, media management, and performance and caching work.',
  array['Featured', 'Full-stack'],
  null,
  array[
    'Product/catalog and repair-related functionality',
    'Admin dashboard and APIs',
    'Data and media management',
    'Performance and caching',
    'Website development'
  ],
  'Technical / Full-Stack Developer at FixTech AS. Work includes the areas described above.',
  null,
  array['AI repair-triage feature is planned / in development.'],
  '[]'::jsonb,
  array['house-of-shawarma', 'sallora'], 3
),
(
  'sallora', 'Sallora',
  'An e-commerce / webshop project with authentication, product browsing, payments, and email functionality.',
  'A full-stack webshop project covering e-commerce, authentication, products, payments through Stripe and Vipps, email, and media management.',
  array['Full-stack'],
  null,
  array[
    'E-commerce and product functionality',
    'Authentication',
    'Stripe and Vipps payments',
    'Email and media management'
  ],
  null, null, '{}', '[]'::jsonb,
  array['pickbox', 'house-of-shawarma'], 4
),
(
  'study-room-booking', 'Study Room Booking Tool',
  'A university project for finding rooms, checking availability, and managing study-room bookings.',
  'An ASP.NET Core MVC application with rooms, bookings, availability, CRUD functionality, validation, and persistent storage in SQLite.',
  array['Full-stack', 'University'],
  null,
  array[
    'Room and booking management',
    'Availability',
    'Create, read, update, and delete operations',
    'Validation and database persistence'
  ],
  null, null, '{}', '[]'::jsonb,
  array['house-of-shawarma', 'sallora'], 5
)
on conflict (slug) do update set
  name = excluded.name,
  summary = excluded.summary,
  description = excluded.description,
  categories = excluded.categories,
  technology_heading = excluded.technology_heading,
  features = excluded.features,
  contribution = excluded.contribution,
  status = excluded.status,
  planned = excluded.planned,
  metrics = excluded.metrics,
  related_project_slugs = excluded.related_project_slugs,
  sort_order = excluded.sort_order;

insert into public.technologies (name) values
  ('Next.js'), ('TypeScript'), ('Supabase'), ('PostgreSQL'), ('Stripe'),
  ('Cloudinary'), ('MongoDB'), ('Mongoose'), ('Resend'), ('Redis'),
  ('Tailwind CSS'), ('Zustand'), ('Zod'), ('C#'), ('ASP.NET Core MVC'),
  ('Entity Framework Core'), ('SQLite'), ('Razor'), ('Bootstrap'), ('JavaScript'),
  ('Expo'), ('React Native'), ('NextAuth'), ('Vipps')
on conflict (name) do nothing;

insert into public.project_technologies (project_slug, technology_id, sort_order)
select mapping.project_slug, technologies.id, mapping.sort_order
from (values
  ('pickbox', 'Next.js', 1), ('pickbox', 'TypeScript', 2),
  ('pickbox', 'Supabase', 3), ('pickbox', 'PostgreSQL', 4),
  ('pickbox', 'Stripe', 5), ('pickbox', 'Cloudinary', 6),
  ('house-of-shawarma', 'Next.js', 1), ('house-of-shawarma', 'TypeScript', 2),
  ('house-of-shawarma', 'MongoDB', 3), ('house-of-shawarma', 'Mongoose', 4),
  ('house-of-shawarma', 'Stripe', 5), ('house-of-shawarma', 'Cloudinary', 6),
  ('house-of-shawarma', 'Resend', 7), ('house-of-shawarma', 'Redis', 8),
  ('fixtech', 'Next.js', 1), ('fixtech', 'TypeScript', 2),
  ('fixtech', 'MongoDB', 3), ('fixtech', 'Mongoose', 4),
  ('fixtech', 'Tailwind CSS', 5), ('fixtech', 'Zustand', 6),
  ('fixtech', 'Zod', 7), ('fixtech', 'Cloudinary', 8),
  ('fixtech', 'Resend', 9), ('fixtech', 'Redis', 10),
  ('sallora', 'Next.js', 1), ('sallora', 'TypeScript', 2),
  ('sallora', 'Tailwind CSS', 3), ('sallora', 'Zustand', 4),
  ('sallora', 'MongoDB', 5), ('sallora', 'NextAuth', 6),
  ('sallora', 'Stripe', 7), ('sallora', 'Vipps', 8),
  ('sallora', 'Resend', 9), ('sallora', 'Cloudinary', 10),
  ('study-room-booking', 'C#', 1), ('study-room-booking', 'ASP.NET Core MVC', 2),
  ('study-room-booking', 'Entity Framework Core', 3), ('study-room-booking', 'SQLite', 4),
  ('study-room-booking', 'Razor', 5), ('study-room-booking', 'Bootstrap', 6),
  ('study-room-booking', 'JavaScript', 7)
) as mapping(project_slug, technology_name, sort_order)
join public.technologies on technologies.name = mapping.technology_name
on conflict (project_slug, technology_id) do update set sort_order = excluded.sort_order;

insert into public.experiences (
  slug, organization, role, start_date, end_date, summary, responsibilities, sort_order
) values (
  'fixtech-as', 'FixTech AS', 'Technical / Full-Stack Developer', '2025-12-01', null,
  'Developing FixTech''s website and product functionality across catalog, repair, administration, APIs, data, and media management.',
  array[
    'Develop website functionality.',
    'Work on product/catalog and repair-related features.',
    'Develop admin dashboard features and APIs.',
    'Manage data and media, and contribute to performance and caching.'
  ], 1
)
on conflict (slug) do update set
  organization = excluded.organization,
  role = excluded.role,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  summary = excluded.summary,
  responsibilities = excluded.responsibilities,
  sort_order = excluded.sort_order;

insert into public.experience_technologies (experience_slug, technology_id, sort_order)
select 'fixtech-as', technologies.id, mapping.sort_order
from (values
  ('Next.js', 1), ('TypeScript', 2), ('MongoDB', 3), ('Mongoose', 4),
  ('Tailwind CSS', 5), ('Zustand', 6), ('Zod', 7), ('Cloudinary', 8),
  ('Resend', 9), ('Redis', 10)
) as mapping(technology_name, sort_order)
join public.technologies on technologies.name = mapping.technology_name
on conflict (experience_slug, technology_id) do update set sort_order = excluded.sort_order;

insert into public.events (
  slug, name, organization, type, date_label, description, learning, people,
  related_project_slug, sort_order
) values
(
  'pangstart', 'Pangstart', 'LIUS', 'Startup / entrepreneurship program', null,
  'A startup and entrepreneurship program where I continued developing PickBox. I had built the PickBox website/MVP before the program.',
  '{}',
  '[{"role":"Mentor","names":["Marius"]},{"role":"Organizers","names":["Kim (LIUS)","Stian"]},{"role":"Other participants","names":["Marcus","Jakob","Silje"]}]'::jsonb,
  'pickbox', 1
),
(
  'telenor-bla-sone', 'Telenor Blå Sone', 'Telenor, Fornebu',
  'Technology / career event', null,
  'A technology and career event that included "En utviklers hverdag", technical discussions, a coding/technical challenge, cybersecurity discussions, and product and technology perspectives.',
  array[
    'I was particularly interested in cybersecurity and CSOC-related work, including AI-supported security workflows and automated response.',
    'I spoke with people working in cybersecurity and technology.'
  ],
  '[]'::jsonb, null, 2
),
(
  'gjensidige-career-day', 'Gjensidige Career Day', 'Gjensidige',
  'Career day / professional development', null,
  'Participation in a career-related event offering exposure to the technology and business environment.',
  '{}', '[]'::jsonb, null, 3
)
on conflict (slug) do update set
  name = excluded.name,
  organization = excluded.organization,
  type = excluded.type,
  date_label = excluded.date_label,
  description = excluded.description,
  learning = excluded.learning,
  people = excluded.people,
  related_project_slug = excluded.related_project_slug,
  sort_order = excluded.sort_order;

insert into public.event_tags (event_slug, tag, sort_order)
select mapping.event_slug, mapping.tag, mapping.sort_order
from (values
  ('pangstart', 'Market research', 1),
  ('pangstart', 'Competitor research', 2),
  ('pangstart', 'Interviews', 3),
  ('pangstart', 'Customer research', 4),
  ('pangstart', 'Business model', 5),
  ('pangstart', 'Product development', 6),
  ('pangstart', 'Pitching', 7),
  ('telenor-bla-sone', 'Software development', 1),
  ('telenor-bla-sone', 'Technical challenge', 2),
  ('telenor-bla-sone', 'Cybersecurity', 3),
  ('telenor-bla-sone', 'Product and technology', 4)
) as mapping(event_slug, tag, sort_order)
on conflict (event_slug, tag) do update set sort_order = excluded.sort_order;
