create table if not exists public.event_images (
  id bigint generated by default as identity primary key,
  event_slug text not null references public.events(slug) on delete cascade,
  src text not null,
  alt text not null,
  caption text,
  sort_order integer not null default 0,
  public_id text,
  width integer,
  height integer,
  format text,
  bytes integer,
  created_at timestamptz not null default now()
);

create unique index if not exists event_images_event_public_id_key
  on public.event_images (event_slug, public_id)
  where public_id is not null;

create index if not exists event_images_event_sort_idx
  on public.event_images (event_slug, sort_order);

alter table public.event_images enable row level security;

create policy "Public can read event images" on public.event_images
  for select to anon, authenticated using (
    exists (
      select 1 from public.events
      where events.slug = event_images.event_slug and events.published
    )
  );

grant select on public.event_images to anon, authenticated;

comment on column public.event_images.public_id is
  'Cloudinary public_id, e.g. portfolio/events/pangstart/group-photo. Populated by npm run sync:images.';
